## Bulgaria
- Lapai mi huia, Duhai mi: Suck my dick	
- Bit pederast / Pederuga: Faggot
- Cheren pedal: Nigger faggot
- Chickidjya / Chikidziq: Wanker
- Ciganin da te ebe: Be fucked by a gipsy
- Coochka: Bitch
- Mamka mu': Fuck
- Da te eba v guza: Fuck you in the ass
- Da ti eba maikata: I Fuck your mother	
- Kopele: Dickhead
- Kuchka: Bitch
- Shibai se: Fuck yourself
- Ебал съм ти майката жабарска: I fucked your frog mother (!Translitteration needed)
- Da ti eba maikata, pederast nedoaten: Fuck your mother, malnourished pederastf
