## Italy
- Figa: Cunt. Can be also used as space between phrases.
- Cazzo: Dick. Can be also used as space between phrases.
- Merda: Shit
- Frocio: Faggot
- Coglione: Moron
- Puttana tua madre: your mom is a bitch
- Succhiamelo / Succhiami il cazzo / Suca / Puppa / Ciccamelo : Suck my dick
- Baciamelo: Kiss it ( my dick )
- Dio <List of animals and/or adjectives>: God is a <List of animals and/or adjectives>.
  - Most common use: Dio Porco ( God is a pig )
- Gesu <List of animals and/or adjectives>: Jesus is a <List of animals and/or adjectives>.
    - Most common use: Gesu Porco ( God is a pig )
- Madonna <List of animals and/or adjectives>: Holy Mary is a <List of animals and/or adjectives>.
    - Most common use: Madonna Maiala ( Holy Mary is a pig )
- Mangia merda: Eat shit
- Figlio di troia: Son of a bitch
- Vaffanculo / Vai a fare in culo: Go fuck yourself in the ass.
- Faccia da cazzo: (*litteral: Dick like face*) Moron
