## Netherlands
- Achterlijk: Retarded
- Autist: Autistic
- Debiel: Handicapped
- Downie / Mongool: With Down Syndrom
- Kanker: (*You are a*) Cancer
- Krijg de kanker: Get the cancer
- Kankeren: To bitch (*literally: to cancer*)
- Klere: (I hope you take) Cholera
- Minkukel: Retarded
- Pleurislijer / Tering / Teringlijer: (I hope you take) Tuberculosis
- Polio: You had been retarded by Poliomyelitis
- Pokke: (I hope you take) Smallpox
- Stom: Retarded
- Takke:(*You look retarded as you had a*) Stroke
- Tyfus: (I hope you take) Typhoid fever
- Vinkentering: (I hope you take) Finch tuberculosis
- Godverdomme <The Target>: May god dam <The Target>
- Anaalgeneraal: Hyper mega faggot 
- Anusridder: Faggot
- Bitch: Bitch
- Dikzak: Fat bag
- Drol: Turd
- Vuile rot mof: Fucking German
