## Poland
- Kurwa: Whore
- Dziwka / Cipa: Cunt
- Chuj / Kutas: Dick
- Dziwka: Whore
- Certolić się / Pieprzyć / Pierdolić: Fuck
- Ruchać / Rżnąć / Wypierdalać: Fuck someone
- Robić loda: Give a blowjob (*litteral: make ice cream*)
- Ja pierdole: Fuck (*litteral: I'm fucking*)
- Pedał: Faggot
- Gówno: Shit
