## Romania
- Am belit pula: We are fucked (*litteral: We have flayed the penis*)
- Bag pula: I shall now quit what I was doing (*litteral: I insert my penis !*)
- Baga-mi-as pula:  I have just made a mistake (*litteral: I'd insert my penis)
- Bai pula: Listen here, you piece of shit (*litteral: Hey, dick*)
- Ca Pula: That's incorrect (*litteral: Like a dick*)
- Ce Pula Mea ?: What the Fuck (*litteral: What my penis ?*)
- Ce-are pula ca prefectura ?: You are comparing apples and oranges (*litteral:What the dick have to do with the prefect's office ?*)
- Curvă: Bitch
- De pula sa ma treci strada: Just because (*litteral: So you can hold me by the dick in order to help me cross the road*)
- Du-te-n pizda mă-tii: Go in your mother's vagina
- Du-te-n pula me: Fuck off (*litteral: Get out of my dick*)
- Du-te-n pula mea de aici: I can not believe my own eye (*litteral: My eyes are going to my dick*)
- Ete pula: No way (*litteral: Behold the dick*)
- Facuta in ciuda pulii: Nice girl (*litteral: Made to spite the penis*)
- Fix pula: Our attempt was futile (*litteral: Exaclty, the dick*)
- Fută-te Dumnniezo: God may Fuck you
- Futu-te-n cur: Fuck you in the ass
- Fu-tu-ți gura mă-tii: Fuck your mother's mouth
- Fu-tu-ți morții și răniții mă-tii: Fuck your mother's dead and injured
- Fu-tu-ți parastasul mă-tii: Fuck your mother's funeral
- Fu-tu-ți Paștele mă-tii: Fuck your mother's Easter
- Hai sictir: Fuck off
- In pula cu satelitul: Very far away (*litteral: On the dick of satellites*)
- In pula mea: I screwed up (*litteral: In my dick*)
- La pulivara: Next fucking sprint (*litteral: Penis-spring*)
- Lindic: Clitoris
- Lua-mi-ai coaiele în gura: Take my balls in your mouth
- Lua-ti-as mortii in pula: I'd stick my dick in your dead ones.
- Ma doare-n pula: I'm super relaxed (*litteral: My dick hurts*)
- Ma fac pula: Im getting drunk (*litteral: I'm becoming a dick*)
- Mai ste pula: I completly forgot (*litteral: Only the dick knows*)
- Mi se rupe pula: I'm overwelgimg relaxed (*litteral: My dick is breaking*)
- Mica-mi-ai pula: Suck my Dick
- Mica-ti-as pula: My dear friend (*litteral: I have to suck your dick*)
- O pula de om: Asshole (*litteral: Not a man, a dick*)
- Pe pula lui: Lucky him (*litteral: On his own penis*)
- Pielea puli: Poor as fuck (*litteral: foreskin*)
- pizda: Vagina
- Pula Mea: I don't know (*litteral: My penis !*)
- Pula nu stie carte: Love is blind (*litteral: The dick doesnt know how to read*)
- Pulă: Dick
- S-a dus pe pula: Fucked up beyond any recognition (*litteral: It went on top of a dick*)
- Să mă bei: drink me
- Să te fut în dinți: Fuck you în the teeth
- Sa-mi bag pula: Wow ! (*litteral: May I insert my penis*)
- Să-mi sugi pula: Suck my Dick
- Si-a Bagat pula: He was rather negligentt at this job (*litteral: He inserted his penis !*)
- The bati pula de mine ?: Are you fucking joking me ? (*litteral: Are you beting me with your dick ?*)
- Un pularau: Ladys male companion (*litteral:Some sort of penis creature*)
- Futi, nu Futi vremea pulii trece: No matter if you Fuck or not, the time of dick quickly passes.
